Upgrade Gemfile to rails ~> 6.1.0. Ran `bin/rails app:update`
Had a problem with database migrations. Ran `rails server` on loading
http://localhost:3000 got complaints like

```
== 20220301075037 AddServiceNameToActiveStorageBlobs: migrating ===============
-- column_exists?(:active_storage_blobs, :service_name)
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

Could not find table 'active_storage_blobs'
```

Found two migrations related to table active_storage_blobs
These were in the wrong order, but before realising that I ran
`rails active_storage:install`
Once I realised my mistake I renamed the database migration file so the
table create came first.
Used `rails db:migrate VERSION=20220301075000` to target that single
migration.
Worked up from there.
Moved duplicate create table migration to db/20220301075038_create_active_storage_variant_records.active_storage.rb